/**
 * Database Models Index 📦
 * =====================
 * Re-exports all Prisma-generated model types, enums, and the core Prisma type.
 * These definitions are automatically generated by Prisma from your 'prisma/schema.prisma' file.
 *
 * NOTE: This barrel file centralizes database entity imports for cleaner application code.
 *
 * It's assumed your 'prisma/schema.prisma' file contains the following models and enums:
 * 
 * Models:
 * - User
 * - StudentProfile
 * - TeacherProfile
 * - Question
 * - Answer
 * - Vote
 * - StorageNode
 * - Category
 * - Resource
 * - Announcement
 * 
 * Enums:
 * - Role
 * - ResourceStatus
 * - CategoryType
 * - Priority
 */

import {
    PrismaClient,
    Role,
    ResourceStatus,
    CategoryType,
    Priority
} from '@prisma/client';

import type {
    User,
    StudentProfile,
    TeacherProfile,
    Question,
    Answer,
    Vote,
    StorageNode,
    Category,
    Resource,
    Announcement,
    Prisma
} from '@prisma/client';

export {
    // Client & Enums
    PrismaClient,
    Role,
    ResourceStatus,
    CategoryType,
    Priority,

    // Models (Types)
    User,
    StudentProfile,
    TeacherProfile,
    Question,
    Answer,
    Vote,
    StorageNode,
    Category,
    Resource,
    Announcement,

    // Prisma Namespace
    Prisma
};

